### ISSUE TITLE
Quick check with the new evaluation code

### ISSUE THREAD

**Issue by weihua916** [hzli-ucas/StarGraph#1]
Hi! This is OGB Team. 

We recently released https://github.com/snap-stanford/ogb/releases/tag/1.3.4 which improves the MRR calculation. This should not change your result if your model makes different predictive scores for different triplets, but would penalize those models that give the same predictive scores for different triplets (which is not ideal for link prediction).

Could you update your ogb package to `1.3.4` and run your model again just to confirm everything stays the same (the dataset stays the same. only evaluator changed)? Just one seed should be enough. Thanks!

**Comment by hzli-ucas** [comment]
Hi @weihua916 ,

We performed a quick recheck, by first updating ogb package to 1.3.4, then evaluationg the pretrained models. We got exactly the same results as before (ogb==1.2.4), accrate to 0.01%.

As we understand, the changes of MRR calculation do not affect the training process, so the re-evaluation results are just enough?

**Comment by weihua916** [comment]
Great! Thanks for confirming. Yes, that's enough. Thanks.
