### ISSUE TITLE
OGB model documentation 

### ISSUE THREAD

**Issue by yperioNas** [hzli-ucas/StarGraph#2]
Good evening. I am sending you, regarding your code for the ogb wikidata. I've been working on graph neural networks lately, but because it's something new to me I'm having difficulties. Could I find somewhere documentation for the code and more specifically for the methods such as TranS or PairRe or RotatE or ComplEx.Thanks in advance.

**Comment by hzli-ucas** [comment]
> Good evening. I am sending you, regarding your code for the ogb wikidata. I've been working on graph neural networks lately, but because it's something new to me I'm having difficulties. Could I find somewhere documentation for the code and more specifically for the methods such as TranS or PairRe or RotatE or ComplEx.Thanks in advance.

Hi, @yperioNas .  Check the [OGB Leaderboard](https://ogb.stanford.edu/docs/leader_linkprop/#ogbl-wikikg2), and Paper/Code for most of the methods can be found there. If any missed, try searching them on Google or Github is a good idea.
Sorry for the delay, didn't get the email in time. Hope everything goes well with your research.
